### ISSUE TITLE
This module is causing "Configure settings menu" to display only half the info

### ISSUE THREAD

**Issue by TrofimSelbs** [mech-tools/one-journal-handouts#1]
Hey, love your module! Thank you for your wonderful work, I am just chiming in to let you know about an issue. 
So while One joirnal handouts is disabled - this issue doesn't reproduce, only when it is enabled. Then I tried and disabled 99% of all modules except this one. It was still reproducing.

On the image you can see that the text in the settings is going away from borders of settings menu. Could you please take a look at it? thank you
![SCR-20240125-rumc](https://github.com/DarKDinDoN/one-journal-handouts/assets/124184162/08629ffa-d450-4108-9a74-201690e4e4ed)

**Comment by mech-tools** [comment]
Hello,

One Journal Handouts is leveraging the default FVTT buttons.

On my end, new world, no modules, no issues:
![image](https://github.com/DarKDinDoN/one-journal-handouts/assets/1687854/1449ea1d-c1ec-482d-973d-ac9efa87c0f0)

Check:
- Others modules (and search for an incompatibility with this module)
- Browser extensions
- Other browser

**Comment by TrofimSelbs** [comment]
thank you for your reply! I've gone over and disabled all modules except ones that I couldn't and it still happening (see that on images, the only module change in Journal). I disabled all extensions on my browser.
I use chrome and the same Foundry build and version as you.... maybe it is a Forge hosting problem

![SCR-20240126-mbda](https://github.com/DarKDinDoN/one-journal-handouts/assets/124184162/e87b93a9-963a-45db-81d4-b5636ab6ceb3)
![SCR-20240126-maob](https://github.com/DarKDinDoN/one-journal-handouts/assets/124184162/36588f8a-a5ff-4220-a828-4c1483de8a22)

**Comment by mech-tools** [comment]
Wait, I think I got it.
Did you create a journal entry with an insanely long title?

**Comment by mech-tools** [comment]
I believe this is fixed with: [1.1.1](https://github.com/DarKDinDoN/one-journal-handouts/releases/tag/1.1.1)

Please close this issue if this is the case.

**Comment by TrofimSelbs** [comment]
I am not sure, but some of my imported journals have pretty long titles yes. I also have "for players" journal with name in Russian, but I didn't before and it still was happening. Maybe that is it as well?

![image](https://github.com/DarKDinDoN/one-journal-handouts/assets/124184162/b5188e7d-8bd7-43d9-823f-59548917f0e5)

**Comment by TrofimSelbs** [comment]
ok, thank you! will go and check. Thank you for your time and effort!

**Comment by TrofimSelbs** [comment]
> I believe this is fixed with: [1.1.1](https://github.com/DarKDinDoN/one-journal-handouts/releases/tag/1.1.1)
> 
> Please close this issue if this is the case.

it it fixed now! thank you
I used manifest URL coz it wan't updated in Foundry modules's list yet, but it works

**Comment by mech-tools** [comment]
Great!
