### ISSUE TITLE
Module prevents save settings

### ISSUE THREAD

**Issue by IamJayRod** [mech-tools/one-journal-handouts#3]
# Module prevents save settings. 

When module is installed, I cannot save settings. I disabled each of my modules one by one until landing on this one. Below is a screenshot of when clicking on save settings. Instead of saving and closing the window, it highlights and leaves the window open.

![image](https://github.com/user-attachments/assets/961f785a-8b03-488f-a3a1-fecd6b422a02)

**Comment by mech-tools** [comment]
Hello,
Could you tell me the following:
- FVTT Version
- Browser

I'll take a look

**Comment by mech-tools** [comment]
Nervermind, this is fixed with [1.2.2](https://github.com/mech-tools/one-journal-handouts/releases/tag/1.2.2)
